import { useCallback, useEffect, useMemo, useState } from 'react'
import {
  careerAction,
  clearBrowserSave,
  companyAction,
  exportSave,
  familyAction,
  getBrowserSaveMeta,
  getCareer,
  getCompany,
  getFamily,
  getLife,
  getMarketSnapshot,
  getPowerRisk,
  lifeAction,
  powerRiskAction,
  restoreSaveCode,
  saveCurrentGameToBrowser,
} from '../api/client.js'

const TABS = [
  ['overview', '總覽'], ['career', '職涯'], ['family', '家庭'], ['company', '公司'],
  ['power', '權力／法律'], ['life', '人生故事'], ['save', '存檔'],
]
const PARTNER_NAMES = ['若晴', '語彤', '子涵', '心妤', '品妍', '庭安', '子皓', '宇辰', '柏翰', '承恩', '以辰', '書豪']
const PARTNER_JOBS = [
  ['technology', '科技／工程', 170], ['finance', '金融／會計', 155], ['healthcare', '醫療／照護', 150],
  ['management', '企業管理', 175], ['legal', '法律／法遵', 165], ['public', '公共服務', 125],
]
const MEETING_METHODS = ['職場合作', '朋友聚會', '進修課程', '健身房', '咖啡店', '社群活動', '旅行途中', '投資講座']
const PERSONALITIES = ['理性穩健', '外向樂觀', '溫柔細膩', '獨立果斷', '幽默隨和', '企圖心強', '保守務實', '浪漫感性']
const EDUCATION_PATHS = [['balanced', '均衡'], ['academic', '學術'], ['creative', '創意'], ['sports', '運動']]
const GOV_STYLE_LABELS = { far_left: '全民福祉（極左）', left: '社會市場（左）', neutral: '中間平衡', right: '市場保守（右）', far_right: '資本極化（極右）' }
const OFFENSE_LABELS = { inside_info_purchase: '非法取得非公開消息', insider_trading: '內線交易', money_laundering: '洗錢／非法資金處理', market_manipulation: '市場操縱', influence_peddling: '不當關說', organized_crime: '地下組織活動', political_corruption: '非法政治介入' }

function money(value) { return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: Math.abs(Number(value || 0)) >= 10000 ? 0 : 2 }).format(Number(value || 0)) }
function pct(value, digits = 1) { return `${Number(value || 0).toFixed(digits)}%` }
function num(value, digits = 0) { return Number(value || 0).toLocaleString('en-US', { maximumFractionDigits: digits }) }
function randomItem(items) { return items[Math.floor(Math.random() * items.length)] }
function childStage(ageDays) { const y = Number(ageDays || 0) / 365; if (y < 3) return '幼兒'; if (y < 7) return '兒童'; if (y < 13) return '學童'; if (y < 18) return '青少年'; return '成年' }

function Metric({ label, value, hint }) { return <div className="life-metric"><span>{label}</span><strong>{value}</strong>{hint && <small>{hint}</small>}</div> }
function Section({ title, children, actions, className = '' }) { return <section className={`life-card ${className}`}><div className="life-card-title"><h3>{title}</h3>{actions}</div>{children}</section> }
function ActionButton({ children, onClick, disabled, tone = '' }) { return <button type="button" className={`life-action ${tone}`} disabled={disabled} onClick={onClick}>{children}</button> }
function Bar({ label, value }) { const width = Math.max(0, Math.min(100, Number(value || 0))); return <div className="deep-progress"><div className="deep-progress-head"><span>{label}</span><strong>{width.toFixed(1)}</strong></div><div className="deep-progress-track"><i style={{ width: `${width}%` }} /></div></div> }
function KeyValueTable({ rows }) { return <div className="deep-table">{rows.map(([label, value]) => <div className="deep-table-row" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div> }

function Overview({ data }) {
  const snap = data.snapshot || {}, account = snap.account || {}, career = data.career || snap.career || {}, family = (data.family || snap.family || {}).family || {}, company = (data.company || snap.playerCompany || {}).company || {}, power = data.power || snap.powerRisk || {}, life = data.life || snap.life || {}
  return <div className="life-stack">
    <div className="life-metric-grid">
      <Metric label="現金" value={money(account.cash)} /><Metric label="總權益" value={money(account.equity)} /><Metric label="健康" value={`${Number(snap.health ?? 100).toFixed(0)}/100`} /><Metric label="壓力" value={`${Number(snap.stress ?? 0).toFixed(0)}/100`} />
      <Metric label="職涯" value={career.currentJob?.name || '待業'} hint={career.employer || ''} /><Metric label="家庭" value={family.married ? `已婚・${family.children || 0} 子女` : family.dating ? '交往中' : '單身'} /><Metric label="公司" value={company.exists ? company.name : '尚未創業'} hint={company.public ? '已上市 MYCO' : company.exists ? '私人公司' : ''} /><Metric label="法律 Heat" value={Number(power.legal?.heat || 0).toFixed(1)} hint={power.legal?.case?.stage || '無案件'} />
    </div>
    {life.pendingEvent && <Section title="目前需要你決定" className="deep-alert-card"><div className="decision-highlight"><strong>{life.pendingEvent.title}</strong><p>{life.pendingEvent.desc}</p><small>期限 Day {life.pendingEvent.deadline_day || life.pendingEvent.deadlineDay || '—'}</small></div></Section>}
    <Section title="這段人生"><div className="life-summary-row"><span>Day {snap.day || 1}</span><span>{Number(snap.age || 25).toFixed(1)} 歲</span><span>XP {life.xp || 0}</span><span>聲望 {Number(life.reputation || career.reputation || 50).toFixed(0)}</span><span>故事記憶 {life.memories?.length || 0}</span><span>待續事件 {life.followupCount || 0}</span></div></Section>
  </div>
}

function CareerPanel({ career, busy, run }) {
  const current = career.currentJob, skills = Object.entries(career.skills || {}), jobs = career.jobs || []
  const [jobId, setJobId] = useState('')
  useEffect(() => { if (!jobId && jobs.length) setJobId(jobs[0].id) }, [jobId, jobs])
  const target = jobs.find((j) => j.id === jobId)
  return <div className="life-stack">
    <div className="life-metric-grid compact"><Metric label="目前職位" value={current?.name || '待業'} /><Metric label="日薪" value={money(current?.dailySalary)} /><Metric label="職涯經驗" value={`${career.experienceDays || 0} 天`} /><Metric label="任職年資" value={`${career.employerDays || 0} 天`} /><Metric label="滿意度" value={Number(career.satisfaction || 0).toFixed(0)} /><Metric label="穩定度" value={Number(career.stability || 0).toFixed(0)} /><Metric label="聲望" value={Number(career.reputation || 0).toFixed(0)} /><Metric label="雇主" value={career.employer || '—'} /></div>
    <Section title="職涯操作"><div className="life-action-row wrap"><ActionButton disabled={busy || !current?.promotionTo} onClick={() => run(careerAction, 'promote', {})}>爭取升遷</ActionButton><ActionButton disabled={busy || current?.id === 'unemployed'} tone="danger" onClick={() => run(careerAction, 'quit', {})}>離職</ActionButton></div><div className="inline-form"><select value={jobId} onChange={(e) => setJobId(e.target.value)}>{jobs.map((j) => <option key={j.id} value={j.id}>{j.name}・技能 Lv.{j.requiredLevel}・{money(j.dailySalary)}/日</option>)}</select><ActionButton disabled={busy || !jobId} onClick={() => run(careerAction, 'apply_job', { jobId })}>應徵</ActionButton></div>{target && <div className="deep-note">{target.description}｜最低經驗 {target.minExperienceDays} 天</div>}</Section>
    <Section title="技能與訓練">{career.training && <div className="status-banner">訓練中：{career.training.skill} → Lv.{career.training.target_level}，剩 {career.training.remaining_days} 日</div>}<div className="skill-grid">{skills.map(([key, skill]) => <div className="skill-row" key={key}><div><strong>{skill.name}</strong><span>Lv.{skill.level}</span></div><ActionButton disabled={busy || Boolean(career.training) || skill.level >= 3} onClick={() => run(careerAction, 'start_training', { skill: key, targetLevel: skill.level + 1 })}>訓練</ActionButton></div>)}</div></Section>
  </div>
}

function FamilyPanel({ familyData, busy, run }) {
  const f = familyData.family || {}, buffs = familyData.buffs || {}
  const [profile, setProfile] = useState({ name: randomItem(PARTNER_NAMES), job: 'technology', income: 170, age: 25, meeting: randomItem(MEETING_METHODS), personality: randomItem(PERSONALITIES) })
  const [childName, setChildName] = useState('安安'), [educationPath, setEducationPath] = useState('balanced'), [educationAmount, setEducationAmount] = useState(5000)
  const [settings, setSettings] = useState({ reserve: 10000, relationship: 70, parenting: 30, dating: 7 })
  useEffect(() => setSettings({ reserve: Number(f.auto_family_cash_reserve ?? 10000), relationship: Number(f.auto_relationship_threshold ?? 70), parenting: Number(f.auto_parenting_interval_days ?? 30), dating: Number(f.auto_dating_interval_days ?? 7) }), [f.auto_family_cash_reserve, f.auto_relationship_threshold, f.auto_parenting_interval_days, f.auto_dating_interval_days])
  function randomizePartner() { const [job, , income] = randomItem(PARTNER_JOBS); setProfile({ name: randomItem(PARTNER_NAMES), job, income, age: 22 + Math.floor(Math.random() * 18), meeting: randomItem(MEETING_METHODS), personality: randomItem(PERSONALITIES) }) }
  function startDating() { run(familyAction, 'start_dating', { partnerName: profile.name, partnerJob: profile.job, partnerDailyIncome: profile.income, partnerAge: profile.age, partnerMeetingMethod: profile.meeting, partnerPersonality: profile.personality }) }
  return <div className="life-stack">
    <div className="life-metric-grid compact"><Metric label="關係" value={Number(f.relationship || 0).toFixed(0)} /><Metric label="幸福" value={Number(f.happiness || 0).toFixed(0)} /><Metric label="伴侶" value={f.partner_name || '無'} hint={f.partner_job || ''} /><Metric label="子女" value={String(f.children || 0)} /><Metric label="昨日家庭收入" value={money(f.last_family_income)} /><Metric label="昨日家庭支出" value={money(f.last_family_expense)} /><Metric label="昨日淨額" value={money(f.last_family_net)} /><Metric label="累計家庭支援" value={money(f.family_support_total)} /></div>

    {!f.dating && !f.married && <Section title="相遇與交往"><div className="deep-family-profile"><div><span>姓名</span><strong>{profile.name}</strong></div><div><span>相遇方式</span><strong>{profile.meeting}</strong></div><div><span>個性</span><strong>{profile.personality}</strong></div><div><span>年齡</span><strong>{profile.age} 歲</strong></div></div><div className="form-grid two"><label><span>姓名</span><input value={profile.name} onChange={(e) => setProfile({ ...profile, name: e.target.value })} /></label><label><span>職涯</span><select value={profile.job} onChange={(e) => { const row = PARTNER_JOBS.find((j) => j[0] === e.target.value); setProfile({ ...profile, job: e.target.value, income: row?.[2] || profile.income }) }}>{PARTNER_JOBS.map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label><span>日收入</span><input type="number" value={profile.income} onChange={(e) => setProfile({ ...profile, income: Number(e.target.value) })} /></label><label><span>年齡</span><input type="number" min="18" max="90" value={profile.age} onChange={(e) => setProfile({ ...profile, age: Number(e.target.value) })} /></label><label><span>相遇方式</span><select value={profile.meeting} onChange={(e) => setProfile({ ...profile, meeting: e.target.value })}>{MEETING_METHODS.map((x) => <option key={x}>{x}</option>)}</select></label><label><span>個性</span><select value={profile.personality} onChange={(e) => setProfile({ ...profile, personality: e.target.value })}>{PERSONALITIES.map((x) => <option key={x}>{x}</option>)}</select></label></div><div className="life-action-row"><ActionButton disabled={busy} onClick={randomizePartner}>重新隨機</ActionButton><ActionButton disabled={busy || !profile.name.trim()} onClick={startDating}>開始交往</ActionButton></div></Section>}

    {(f.dating || f.married) && <Section title="伴侶與關係"><div className="deep-grid-3"><Metric label="相遇方式" value={f.partner_meeting_method || '—'} /><Metric label="個性" value={f.partner_personality || '—'} /><Metric label="職涯 Lv." value={`Lv.${f.partner_level || 1}`} /><Metric label="伴侶日收入" value={money(f.partner_daily_income)} /><Metric label="伴侶年齡" value={`${Number(f.partner_age || 0).toFixed(1)} 歲`} /><Metric label="婚姻天數" value={`${f.marriage_days || 0} 天`} /></div><div className="deep-progress-pair"><Bar label="關係" value={f.relationship} /><Bar label="幸福" value={f.happiness} /></div>{f.dating && <div className="life-action-row"><ActionButton disabled={busy} onClick={() => run(familyAction, 'talk', {})}>聊天／約會 $200</ActionButton><ActionButton disabled={busy} onClick={() => run(familyAction, 'marry', {})}>結婚</ActionButton></div>}{f.married && <div className="deep-note">穩定後盾：{f.stable_support_unlocked ? '已解鎖' : `累積中（${f.high_happiness_streak || 0}/365 天）`}｜長照累計 {money(f.long_term_care_total)}</div>}</Section>}

    {f.married && <Section title="家庭管理"><div className="inline-form"><input value={childName} onChange={(e) => setChildName(e.target.value)} placeholder="孩子姓名" /><select value={educationPath} onChange={(e) => setEducationPath(e.target.value)}>{EDUCATION_PATHS.map(([key, label]) => <option key={key} value={key}>{label}教育</option>)}</select><ActionButton disabled={busy || !childName.trim()} onClick={() => run(familyAction, 'add_child', { name: childName, educationPath })}>新增子女</ActionButton></div><div className="deep-settings-grid"><label className="toggle-row compact-toggle"><span>自動家庭照顧</span><input type="checkbox" checked={Boolean(f.auto_family_care)} onChange={(e) => run(familyAction, 'settings', { autoFamilyCare: e.target.checked })} /></label><label><span>保留現金</span><input type="number" value={settings.reserve} onChange={(e) => setSettings({ ...settings, reserve: Number(e.target.value) })} /></label><label><span>關係門檻</span><input type="number" value={settings.relationship} onChange={(e) => setSettings({ ...settings, relationship: Number(e.target.value) })} /></label><label><span>育兒間隔</span><input type="number" value={settings.parenting} onChange={(e) => setSettings({ ...settings, parenting: Number(e.target.value) })} /></label><label><span>約會間隔</span><input type="number" value={settings.dating} onChange={(e) => setSettings({ ...settings, dating: Number(e.target.value) })} /></label><ActionButton disabled={busy} onClick={() => run(familyAction, 'settings', { autoFamilyCare: Boolean(f.auto_family_care), autoFamilyCashReserve: settings.reserve, autoRelationshipThreshold: settings.relationship, autoParentingIntervalDays: settings.parenting, autoDatingIntervalDays: settings.dating })}>儲存</ActionButton></div></Section>}

    <Section title="家庭加成"><div className="deep-chip-row"><span>減壓 {Number(buffs.stress_relief || 0).toFixed(2)}</span><span>升遷 +{pct((buffs.promotion_bonus || 0) * 100)}</span><span>疾病 ×{Number(buffs.illness_mult || 1).toFixed(2)}</span><span>公司營收 ×{Number(buffs.company_rev_mult || 1).toFixed(2)}</span><span>罰金 ×{Number(buffs.fine_mult || 1).toFixed(2)}</span><span>伴侶貢獻 {pct((buffs.partner_contribution_rate || 0) * 100)}</span></div></Section>

    {f.child_profiles?.length > 0 && <Section title="子女教育與下一代" actions={<div className="inline-form compact-inline"><input type="number" min="100" step="500" value={educationAmount} onChange={(e) => setEducationAmount(Number(e.target.value))} /></div>}><div className="deep-child-grid">{f.child_profiles.map((c, i) => <article className="deep-child-card" key={`${c.name}-${i}`}><div className="deep-child-head"><div><strong>{c.name}</strong><span>{childStage(c.age_days)}・{(Number(c.age_days || 0) / 365).toFixed(1)} 歲</span></div><b>教育 Lv.{c.education_level || 0}</b></div><div className="deep-chip-row"><span>教育基金 {money(c.education_fund)}</span><span>路線 {EDUCATION_PATHS.find((x) => x[0] === c.education_path)?.[1] || c.education_path}</span>{Number(c.adult_income || 0) > 0 && <span>{c.adult_career}・{money(c.adult_income)}/日</span>}</div><div className="deep-progress-stack"><Bar label="學習" value={c.learning} /><Bar label="自信" value={c.confidence} /><Bar label="親密" value={c.parent_bond} /><Bar label="興趣" value={c.interest} /></div>{childStage(c.age_days) !== '成年' && <><div className="inline-form"><select value={c.education_path || 'balanced'} onChange={(e) => run(familyAction, 'set_child_path', { index: i, educationPath: e.target.value })}>{EDUCATION_PATHS.map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><ActionButton disabled={busy} onClick={() => run(familyAction, 'fund_child_education', { index: i, amount: educationAmount })}>投入教育 {money(educationAmount)}</ActionButton></div><div className="life-action-row"><ActionButton disabled={busy} onClick={() => run(familyAction, 'parent_child', { index: i, cost: 300 })}>陪伴孩子 $300</ActionButton></div></>}</article>)}</div></Section>}

    {(familyData.eventHistory || f.family_event_history)?.length > 0 && <Section title="家庭時間線"><div className="record-list">{(familyData.eventHistory || f.family_event_history || []).slice().reverse().map((row, i) => <div className="record-row" key={`${row.day}-${i}`}><div><strong>Day {row.day}・{row.title}</strong><span>{row.kind}</span></div><p>{row.desc}</p></div>)}</div></Section>}
  </div>
}

function CompanyPanel({ companyData, busy, run }) {
  const c = companyData.company || {}, bs = companyData.balanceSheet || {}, cf = companyData.cashFlow || {}, gov = companyData.governance || {}, op = companyData.operating || {}, debt = companyData.debt || {}, cap = companyData.capacity || {}, research = companyData.research || {}, ipo = companyData.ipo || {}
  const [found, setFound] = useState({ name: 'MYCO', industry: 'software', capital: 65000, employees: 3 }), [amount, setAmount] = useState(10000), [releaseRatio, setReleaseRatio] = useState(.25), [payout, setPayout] = useState(Number(c.dividend_payout_ratio || 0))
  useEffect(() => setPayout(Number(c.dividend_payout_ratio || 0)), [c.dividend_payout_ratio])
  if (!companyData.exists) return <Section title="成立公司"><div className="form-grid two"><label><span>名稱</span><input value={found.name} onChange={(e) => setFound({ ...found, name: e.target.value })} /></label><label><span>產業</span><select value={found.industry} onChange={(e) => setFound({ ...found, industry: e.target.value })}><option value="software">軟體</option><option value="finance">金融</option><option value="health">醫療</option><option value="manufacturing">製造</option><option value="logistics">物流</option><option value="retail">零售</option></select></label><label><span>投入資本</span><input type="number" value={found.capital} onChange={(e) => setFound({ ...found, capital: Number(e.target.value) })} /></label><label><span>初始員工</span><input type="number" min="1" max="25" value={found.employees} onChange={(e) => setFound({ ...found, employees: Number(e.target.value) })} /></label></div><ActionButton disabled={busy} onClick={() => run(companyAction, 'found', found)}>成立公司</ActionButton></Section>
  const ipoLabels = { exists: '公司存在', notPublic: '尚未上市', age: '公司年齡', quarterRevenue: '季度營收', valuation: '估值', cash: '公司現金', employees: '員工', brand: '品牌', profitableQuarters: '獲利季度', notBankrupt: '非破產' }
  return <div className="life-stack">
    <div className="life-metric-grid compact"><Metric label="公司" value={c.name} hint={c.public ? 'Public / MYCO' : 'Private'} /><Metric label="估值" value={money(c.valuation)} /><Metric label="公司現金" value={money(c.cash)} /><Metric label="負債" value={money(c.debt)} /><Metric label="員工" value={num(c.employees)} /><Metric label="今日營收" value={money(c.daily_revenue)} /><Metric label="今日淨利" value={money(c.daily_profit)} /><Metric label="玩家持股" value={pct(companyData.ownershipPct || 100)} /><Metric label="營運狀態" value={op.label || '—'} hint={`Runway ${Number(op.runwayDays || 0) >= 9999 ? '∞' : `${Number(op.runwayDays || 0).toFixed(1)} 天`}`} /><Metric label="董事會支持" value={`${Number(gov.boardSupport || 0).toFixed(0)}/100`} hint={gov.ceoControl ? 'CEO 控制權正常' : '重大行動受限'} /><Metric label="產能利用" value={pct((cap.utilization || 0) * 100)} /><Metric label="研發／人" value={money(research.perEmployee)} /></div>

    <div className="deep-two-column"><Section title="資產負債表"><KeyValueTable rows={[["現金", money(bs.cash)], ["應收帳款", money(bs.accountsReceivable)], ["庫存", money(bs.inventory)], ["固定資產", money(bs.fixedAssets)], ["研發資產", money(bs.rdAsset)], ["總資產", money(bs.totalAssets)], ["負債", money(bs.debt)], ["股東權益", money(bs.equity)], ["負債／資產", pct((bs.debtToAssets || 0) * 100)]]} /></Section><Section title="現金流量表"><KeyValueTable rows={[["今日營運現金流", money(cf.dailyOperating)], ["今日自由現金流", money(cf.dailyFree)], ["上季營運現金流", money(cf.lastQuarterOperating)], ["上季投資現金流", money(cf.lastQuarterInvesting)], ["上季融資現金流", money(cf.lastQuarterFinancing)], ["上季自由現金流", money(cf.lastQuarterFree)], ["上季 CAPEX", money(cf.lastQuarterCapex)]]} /></Section></div>

    <Section title="營運與投資"><div className="life-action-row wrap"><ActionButton disabled={busy} onClick={() => run(companyAction, 'hire', { count: 1 })}>聘 1 人</ActionButton><ActionButton disabled={busy} onClick={() => run(companyAction, 'layoff', { count: 1 })}>裁 1 人</ActionButton></div><div className="inline-form"><input type="number" min="0" value={amount} onChange={(e) => setAmount(Number(e.target.value))} /><ActionButton disabled={busy} onClick={() => run(companyAction, 'invest_rd', { amount })}>研發</ActionButton><ActionButton disabled={busy} onClick={() => run(companyAction, 'invest_assets', { amount })}>CAPEX</ActionButton><ActionButton disabled={busy} onClick={() => run(companyAction, 'invest_brand', { amount })}>品牌</ActionButton></div><div className="deep-note">固定資產可支援約 {Number(cap.supportedEmployees || 0).toFixed(1)} 人；研發生產力加成 {pct((research.productivityBonus || 0) * 100)}；毛利加成 {pct((research.marginBonus || 0) * 100)}。</div></Section>

    <Section title="資本結構與治理"><div className="deep-chip-row"><span>借款利率 {pct((debt.annualRate || 0) * 100, 2)}</span><span>可新增負債 {money(companyData.debtCapacity)}</span><span>流動性壓力 {gov.liquidityDistressDays || 0} 天</span><span>緊急信用 {money(gov.emergencyCreditUsed)}</span><span>重整 {gov.restructuringCount || 0} 次</span></div><div className="life-action-row wrap"><ActionButton disabled={busy} onClick={() => run(companyAction, 'borrow', { amount })}>借款</ActionButton><ActionButton disabled={busy} onClick={() => run(companyAction, 'repay_debt', { amount })}>還債</ActionButton><ActionButton disabled={busy} onClick={() => run(companyAction, 'inject_capital', { amount })}>個人注資</ActionButton><ActionButton disabled={busy} onClick={() => run(companyAction, 'emergency_credit', { amount })}>緊急信用</ActionButton><ActionButton disabled={busy} onClick={() => run(companyAction, 'board_reform', { amount })}>治理改善</ActionButton>{(c.bankrupt || Number(gov.liquidityDistressDays || 0) >= 20) && <ActionButton disabled={busy} tone="danger" onClick={() => run(companyAction, 'restructure', {})}>公司重整</ActionButton>}</div></Section>

    {!c.public && <Section title="IPO 準備" actions={<span className={`status-pill ${ipo.ready ? 'good' : ''}`}>{ipo.ready ? '可申請上市' : '尚未達標'}</span>}><div className="deep-check-grid">{Object.entries(ipo.checks || {}).map(([key, ok]) => <div className={ok ? 'passed' : ''} key={key}>{ok ? '✓' : '○'} {ipoLabels[key] || key}</div>)}</div><div className="inline-form"><label><span>釋股比例</span><input type="number" min="10" max="45" value={Math.round(releaseRatio * 100)} onChange={(e) => setReleaseRatio(Number(e.target.value) / 100)} /></label><ActionButton disabled={busy || !ipo.ready} onClick={() => run(companyAction, 'ipo', { releaseRatio })}>正式 IPO</ActionButton></div></Section>}

    {c.public && <Section title="上市公司資本政策"><div className="inline-form"><label><span>配息率 0～60%</span><input type="number" min="0" max="60" value={Math.round(payout * 100)} onChange={(e) => setPayout(Number(e.target.value) / 100)} /></label><ActionButton disabled={busy} onClick={() => run(companyAction, 'set_dividend', { payoutRatio: payout })}>設定配息</ActionButton><ActionButton disabled={busy} onClick={() => run(companyAction, 'issue_shares', { ratio: .05 })}>增發 5%</ActionButton><ActionButton disabled={busy} onClick={() => run(companyAction, 'buyback', { ratio: .03 })}>回購 3%</ActionButton></div></Section>}

    <Section title="季度財報歷史"><div className="record-list">{(c.history || []).slice().reverse().map((h, i) => <div className="record-row" key={`${h.day}-${i}`}><div><strong>Day {h.day}・季度財報</strong><span>{money(h.profit ?? h.daily_profit)}</span></div><p>營收 {money(h.revenue)}｜OCF {money(h.operatingCashFlow)}｜FCF {money(h.freeCashFlow)}｜稅 {money(h.tax)}｜CAPEX {money(h.capex)}</p></div>)}{!c.history?.length && <div className="empty-state">尚未完成第一季</div>}</div></Section>
  </div>
}

function PowerPanel({ power, market, busy, run }) {
  const politics = power.politics || {}, underworld = power.underworld || {}, legal = power.legal || {}, insider = power.insider || {}
  const [donation, setDonation] = useState(10000), [insideSymbol, setInsideSymbol] = useState(market?.assets?.[0]?.symbol || 'AAPL'), [insideSource, setInsideSource] = useState('skill'), [stake, setStake] = useState(5000), [defense, setDefense] = useState(5000)
  return <div className="life-stack">
    <div className="life-metric-grid compact"><Metric label="政治 Lv." value={politics.level || 0} /><Metric label="影響力" value={Number(politics.influence || 0).toFixed(1)} /><Metric label="政治信任" value={Number(politics.trust || 0).toFixed(1)} /><Metric label="政府風格" value={GOV_STYLE_LABELS[politics.governmentStyle] || politics.governmentStyle || '中立'} /><Metric label="地下勢力" value={`Lv.${underworld.rank || 0}`} /><Metric label="非法資金" value={money(underworld.dirtyMoney)} /><Metric label="Legal Heat" value={Number(legal.heat || 0).toFixed(1)} /><Metric label="案件" value={legal.case?.stage || '無案件'} /></div>
    <Section title="政治與政策方向"><div className="life-action-row"><ActionButton disabled={busy || politics.level >= 3} onClick={() => run(powerRiskAction, 'train_politics', { targetLevel: (politics.level || 0) + 1 })}>政治訓練</ActionButton></div><div className="inline-form"><input type="number" value={donation} onChange={(e) => setDonation(Number(e.target.value))} /><ActionButton disabled={busy || politics.level < 1} onClick={() => run(powerRiskAction, 'donate', { amount: donation, direction: -.75 })}>倡議偏左</ActionButton><ActionButton disabled={busy || politics.level < 1} onClick={() => run(powerRiskAction, 'donate', { amount: donation, direction: 0 })}>中性倡議</ActionButton><ActionButton disabled={busy || politics.level < 1} onClick={() => run(powerRiskAction, 'donate', { amount: donation, direction: .75 })}>倡議偏右</ActionButton></div><div className="deep-note">政府偏向 {Number(politics.governmentBias || 0).toFixed(3)}｜累計政治投入 {money(politics.donationsTotal)}</div></Section>
    <Section title="地下勢力"><div className="life-action-row wrap"><ActionButton disabled={busy || underworld.rank >= 3} onClick={() => run(powerRiskAction, 'train_underworld', { targetLevel: (underworld.rank || 0) + 1 })}>提升勢力</ActionButton><ActionButton disabled={busy || !underworld.dirtyMoney} onClick={() => run(powerRiskAction, 'launder', { amount: underworld.dirtyMoney })}>處理全部非法資金</ActionButton><ActionButton disabled={busy || underworld.rank < 1} onClick={() => run(powerRiskAction, 'pause_underworld', { paused: !underworld.paused })}>{underworld.paused ? '恢復活動' : '暫停活動'}</ActionButton></div><div className="deep-note">累計非法收入 {money(underworld.totalEarned)}。此路線會增加法律風險並可能形成刑事案件。</div></Section>
    <Section title="非公開消息／內線風險"><div className="inline-form"><select value={insideSymbol} onChange={(e) => setInsideSymbol(e.target.value)}>{(market?.assets || []).map((a) => <option key={a.symbol} value={a.symbol}>{a.displayTicker || a.symbol}</option>)}</select><select value={insideSource} onChange={(e) => setInsideSource(e.target.value)}><option value="skill">職業技能</option><option value="politics">政治管道</option><option value="underworld">地下管道</option></select><ActionButton disabled={busy} onClick={() => run(powerRiskAction, 'buy_inside_info', { symbol: insideSymbol, source: insideSource, skill: 'finance' })}>取得消息</ActionButton></div>{insider.tip && <div className="status-banner">{insider.tip.symbol}・{insider.tip.direction}・可信度 {pct((insider.tip.accuracy || 0) * 100)}・有效至 Day {insider.tip.expiresDay}</div>}<div className="inline-form"><input type="number" value={stake} onChange={(e) => setStake(Number(e.target.value))} /><ActionButton disabled={busy || !insider.tip || Boolean(insider.position)} onClick={() => run(powerRiskAction, 'open_insider_position', { stake })}>建立內線部位</ActionButton></div>{insider.position && <div className="deep-note">待結算：{insider.position.symbol}・{insider.position.direction}・投入 {money(insider.position.stake)}・Day {insider.position.resolve_day || insider.position.resolveDay}</div>}</Section>
    <Section title="法律案件"><div className="deep-grid-3"><Metric label="階段" value={legal.case?.stage || '無案件'} /><Metric label="證據" value={Number(legal.case?.evidence || 0).toFixed(1)} /><Metric label="來源" value={legal.case?.source || '—'} /><Metric label="案底" value={legal.criminalRecord ? '有' : '無'} /><Metric label="監禁" value={`${legal.prisonDays || 0} 天`} /><Metric label="Heat" value={Number(legal.heat || 0).toFixed(1)} /></div>{legal.case?.stage && legal.case.stage !== '無案件' && <div className="inline-form"><input type="number" value={defense} onChange={(e) => setDefense(Number(e.target.value))} /><ActionButton disabled={busy} onClick={() => run(powerRiskAction, 'legal_defense', { amount: defense })}>投入法律防禦</ActionButton></div>}<div className="deep-chip-row">{Object.entries(legal.offenses || {}).map(([key, count]) => Number(count) > 0 && <span key={key}>{OFFENSE_LABELS[key] || key} ×{count}</span>)}</div></Section>
    {legal.history?.length > 0 && <Section title="判決／案件紀錄"><div className="record-list">{legal.history.slice().reverse().map((h, i) => <div className="record-row" key={`${h.day}-${i}`}><div><strong>Day {h.day}・{h.trigger || '法律案件'}</strong><span>{h.days || 0} 天</span></div><p>{(h.offenses || []).join('、')}｜罰金 {money(h.fine)}｜政府環境 {GOV_STYLE_LABELS[h.govStyle] || h.govStyle || '—'}</p></div>)}</div></Section>}
  </div>
}

function LifePanel({ life, busy, run }) {
  const pending = life.pendingEvent
  return <div className="life-stack">
    {pending ? <Section title={pending.title || '人生抉擇'}><p className="life-copy">{pending.desc}</p><div className="deep-chip-row"><span>產生 Day {pending.generated_day || pending.generatedDay || '—'}</span><span>期限 Day {pending.deadline_day || pending.deadlineDay || '—'}</span>{pending.followup && <span>後續事件</span>}{pending.named_chain && <span>故事鏈 {pending.named_chain}</span>}</div><div className="choice-grid">{(pending.choices || []).map((choice, index) => <button type="button" className="choice-card" disabled={busy} key={`${choice.label}-${index}`} onClick={() => run(lifeAction, 'resolve', { choiceIndex: index })}><strong>{choice.label}</strong><span>{choice.result || ''}</span><small>現金 {money(choice.cash || 0)}｜健康 {Number(choice.health || 0) >= 0 ? '+' : ''}{choice.health || 0}｜壓力 {Number(choice.stress || 0) >= 0 ? '+' : ''}{choice.stress || 0}｜XP {choice.xp || 0}</small></button>)}</div></Section> : <Section title="人生事件"><div className="empty-state">目前沒有待處理事件；市場與人生仍會隨時間繼續累積故事。</div></Section>}
    <Section title="自動處理策略"><div className="life-action-row wrap"><ActionButton disabled={busy} onClick={() => run(lifeAction, 'set_auto_policy', { policy: 'pause', cashReserve: life.cashReserve || 0 })}>暫停等待</ActionButton><ActionButton disabled={busy} onClick={() => run(lifeAction, 'set_auto_policy', { policy: 'safe', cashReserve: life.cashReserve || 0 })}>保守自動</ActionButton><ActionButton disabled={busy} onClick={() => run(lifeAction, 'set_auto_policy', { policy: 'ignore', cashReserve: life.cashReserve || 0 })}>自動忽略</ActionButton></div><div className="deep-note">目前：{life.autoPolicy || 'pause'}｜保留現金 {money(life.cashReserve)}</div></Section>
    <Section title="長期人生記憶"><div className="record-list">{life.memories?.length ? life.memories.map((m) => <div className="record-row" key={m.key}><div><strong>{m.label}</strong><span>{m.status === 'active' ? '延續中' : '已完成'}・Stage {m.stage}</span></div><p>{m.summary}</p><small>開始 Day {m.startedDay}・最近 Day {m.lastDay}</small></div>) : <div className="empty-state">故事還在累積</div>}</div></Section>
    <Section title="人生選擇時間線"><div className="record-list">{(life.history || []).slice().reverse().map((h, i) => <div className="record-row" key={`${h.day}-${i}`}><div><strong>Day {h.day}・{h.title}</strong><span>{h.choice}</span></div><p>{h.result}</p></div>)}{!life.history?.length && <div className="empty-state">尚無重大人生選擇</div>}</div></Section>
  </div>
}

function SavePanel({ onRestored, busy, setBusy, setNotice }) {
  const [meta, setMeta] = useState(() => getBrowserSaveMeta()), [code, setCode] = useState(''), [exported, setExported] = useState('')
  async function saveNow() { setBusy(true); try { const result = await saveCurrentGameToBrowser(); setMeta(result?.preview || getBrowserSaveMeta()); setExported(result?.code || ''); setNotice('已保存到這個瀏覽器') } catch (e) { setNotice(e.message || '存檔失敗') } finally { setBusy(false) } }
  async function exportNow() { setBusy(true); try { const result = await exportSave(); setExported(result.code || ''); setNotice('已產生可攜式存檔碼') } catch (e) { setNotice(e.message || '匯出失敗') } finally { setBusy(false) } }
  async function restore() { setBusy(true); try { const result = await restoreSaveCode(code.trim()); onRestored(result); setMeta(getBrowserSaveMeta()); setNotice('存檔已恢復') } catch (e) { setNotice(e.message || '恢復失敗') } finally { setBusy(false) } }
  return <div className="life-stack"><Section title="瀏覽器存檔" actions={<div className="life-action-row"><ActionButton disabled={busy} onClick={saveNow}>立即保存</ActionButton><ActionButton disabled={busy} onClick={exportNow}>匯出</ActionButton></div>}>{meta ? <div className="save-preview"><strong>Day {meta.day}</strong><span>{Number(meta.age || 0).toFixed(1)} 歲</span><span>{meta.jobId}</span><span>{money(meta.cash)}</span></div> : <div className="empty-state">尚未在這個瀏覽器保存</div>}<button type="button" className="text-danger" onClick={() => { clearBrowserSave(); setMeta(null) }}>清除瀏覽器存檔</button></Section>{exported && <Section title="可攜式存檔碼"><textarea className="save-code" readOnly value={exported} /></Section>}<Section title="匯入存檔碼"><textarea className="save-code" value={code} onChange={(e) => setCode(e.target.value)} placeholder="貼上 CL181... 存檔碼" /><ActionButton disabled={busy || !code.trim()} onClick={restore}>恢復這段人生</ActionButton></Section></div>
}

export default function LifeCenter({ player, onMarket, onExit, onRestored }) {
  const [tab, setTab] = useState('overview'), [data, setData] = useState({ snapshot: player.snapshot || null, career: null, family: null, company: null, power: null, life: null }), [busy, setBusy] = useState(false), [notice, setNotice] = useState('')
  const load = useCallback(async () => {
    const results = await Promise.allSettled([getMarketSnapshot(), getCareer(), getFamily(), getCompany(), getPowerRisk(), getLife()])
    setData((current) => ({ ...current, snapshot: results[0].status === 'fulfilled' ? results[0].value : current.snapshot, career: results[1].status === 'fulfilled' ? results[1].value : current.career, family: results[2].status === 'fulfilled' ? results[2].value : current.family, company: results[3].status === 'fulfilled' ? results[3].value : current.company, power: results[4].status === 'fulfilled' ? results[4].value : current.power, life: results[5].status === 'fulfilled' ? results[5].value : current.life }))
    const failed = results.find((r) => r.status === 'rejected'); if (failed) setNotice(failed.reason?.message || '部分人生資料載入失敗')
  }, [])
  useEffect(() => { load() }, [load])
  async function run(fn, action, payload) { setBusy(true); setNotice(''); try { const result = await fn(action, payload); if (result?.ok === false) throw new Error(result.message || '操作失敗'); setNotice(result?.message || '操作完成'); await load() } catch (e) { setNotice(e.message || '操作失敗') } finally { setBusy(false) } }
  const snapshot = data.snapshot || {}, account = snapshot.account || {}
  const tabContent = useMemo(() => {
    if (tab === 'career') return data.career ? <CareerPanel career={data.career} busy={busy} run={run} /> : null
    if (tab === 'family') return data.family ? <FamilyPanel familyData={data.family} busy={busy} run={run} /> : null
    if (tab === 'company') return data.company ? <CompanyPanel companyData={data.company} busy={busy} run={run} /> : null
    if (tab === 'power') return data.power ? <PowerPanel power={data.power} market={snapshot} busy={busy} run={run} /> : null
    if (tab === 'life') return data.life ? <LifePanel life={data.life} busy={busy} run={run} /> : null
    if (tab === 'save') return <SavePanel onRestored={onRestored} busy={busy} setBusy={setBusy} setNotice={setNotice} />
    return <Overview data={data} />
  }, [tab, data, busy, snapshot, onRestored])
  return <main className="terminal-shell life-shell"><header className="terminal-topbar life-topbar"><div className="brand-inline"><span>◈</span><strong>資本人生</strong></div><div className="top-stats"><span>Day {snapshot.day || 1}</span><span>{Number(snapshot.age || player.startAge || 25).toFixed(1)} 歲</span><span>現金 <strong>{money(account.cash)}</strong></span><span>權益 <strong>{money(account.equity)}</strong></span></div><div className="mode-switch"><button type="button" className="ghost-button" onClick={onMarket}>📈 市場</button><button type="button" className="ghost-button active">👤 人生／經營</button></div><button type="button" className="ghost-button" onClick={onExit}>主選單</button></header><section className="life-layout"><nav className="life-nav">{TABS.map(([key, label]) => <button type="button" key={key} className={tab === key ? 'active' : ''} onClick={() => setTab(key)}>{label}</button>)}</nav><section className="life-content">{notice && <div className="life-notice">{notice}</div>}{tabContent || <div className="empty-state">載入中…</div>}</section></section></main>
}
